site_name: pyharp
repo_url: "https://github.com/fchampalimaud/pyharp"
# repo_name: "pyharp"

plugins:
  - search
  - autorefs
  - codeinclude
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_submodules: true
            show_source: false
  - git-committers:
      repository: fchampalimaud/pyharp
      branch: main
  - git-authors
            

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - content.tooltips
    - toc.follow
    - content.code.copy
    # - navigation.sections
    - navigation.indexes
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to system preference

nav:
  - Home: index.md
  - Examples:
    - examples/index.md
    - Getting Device Info: examples/get_info.md
    - Check Device ID: examples/check_device_id.md
    - Wait for Events: examples/wait_for_events.md
    - Write and Read from Registers: examples/write_and_read_from_registers.md
  - API:
    - Device: api/device.md
    - Messages: api/messages.md

extra_css:
- stylesheets/extra.css