site_name: pyharp
repo_url: https://github.com/harp-tech/pyharp
repo_name: "harp-tech/pyharp"
copyright: Copyright (c) harp-tech and Contributors

plugins:
  - search
  - autorefs
  - codeinclude
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_submodules: true
            show_source: false
            extensions:
              - griffe_fieldz
  - git-committers:
      repository: harp-tech/pyharp
      branch: main
  - git-authors


markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  features:
    - content.tooltips
    - toc.follow
    - content.code.copy
    - navigation.sections
    - navigation.indexes
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to system preference

nav:
  - Home: index.md
  - Examples:
    - examples/index.md
    - Getting Device Info: examples/get_info/get_info.md
    - Read and Write from Registers: examples/read_and_write_from_registers/read_and_write_from_registers.md
    - Reading Data into a DataFrame: examples/read_data_to_dataframe/read_data_to_dataframe.md
  - API:
    - Protocol: api/protocol.md
    - Serial: api/serial.md
    - Device: api/device.md
    - Data: api/data.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harp-tech/pyharp

extra_css:
- stylesheets/extra.css
