[project]
name = "harp"
version = "0.2.0"
description = "Library for data acquisition and control of devices implementing the Harp protocol."
authors = [{ name= "Hardware and Software Platform, Champalimaud Foundation", email="software@research.fchampalimaud.org"}]
license = "MIT"
readme = 'README.md'
keywords = ['python', 'harp']
requires-python = ">=3.10,<4.0"
dependencies = [
    "harp-protocol",
    "harp-device",
    "harp-serial",
    "harp-data",
]

[project.urls]
Repository = "https://github.com/fchampalimaud/pyharp/"
"Bug Tracker" = "https://github.com/fchampalimaud/pyharp/issues"
Documentation = "https://fchampalimaud.github.io/pyharp/"

[tool.uv.sources]
harp-protocol = { workspace = true }
harp-device = { workspace = true }
harp-serial = { workspace = true }
harp-data = { workspace = true }

[tool.uv.workspace]
members = [
    "src/packages/*",
]

[dependency-groups]
docs = [
    "griffe-fieldz>=0.2.1",
    "mkdocs>=1.6.1",
    "mkdocs-codeinclude-plugin>=0.2.1",
    "mkdocs-git-authors-plugin>=0.9.4",
    "mkdocs-git-committers-plugin-2>=2.5.0",
    "mkdocs-include-markdown-plugin>=7.1.6",
    "mkdocs-material>=9.6.9",
    "mkdocs-monorepo-plugin>=1.1.2",
    "mkdocstrings-python>=1.16.6",
]

dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.0",
    "ty>=0.0.0",
    "harp-protocol",
    "harp-device",
    "harp-serial",
    "harp-data",
    "typing-extensions>=4.15.0",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ["--import-mode=importlib", ]
python_files = [
    "tests.py",
    "test_*.py"
]


[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ty.environment]
python-version = "3.11"
extra-paths = ["tests"]

[tool.ty.src]
include = [
    "src/packages/harp-protocol/src",
    "src/packages/harp-device/src",
    "src/packages/harp-serial/src",
    "src/packages/harp-data/src",
]
exclude = [
    "tests",
]