[project]
name = "harp"
version = "0.0.0"
description = "Library for data acquisition and control of devices implementing the Harp protocol."
authors = [{ name = "harp-tech", email = "contact@harp-tech.org" }]
license = "MIT"
license-files = ["LICENSE"]
readme = 'README.md'
keywords = [
    "harp",
    "harp-protocol",
    "data-acquisition",
    "serial",
    "hardware",
    "device-control",
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: System :: Hardware :: Hardware Drivers",
]
dependencies = [
    "harp-protocol",
    "harp-device",
    "harp-serial",
    "harp-data",
]

[project.urls]
Homepage = "https://harp-tech.org/"
Repository = "https://github.com/harp-tech/pyharp/"
Documentation = "https://harp-tech.org/pyharp/"
"Bug Tracker" = "https://github.com/harp-tech/pyharp/issues"
Changelog = "https://github.com/harp-tech/pyharp/releases"

[build-system]
requires = ["uv_build>=0.9.5"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "harp"
module-root = "src"
namespace = true

[tool.uv.sources]
harp-protocol = { workspace = true }
harp-device = { workspace = true }
harp-serial = { workspace = true }
harp-data = { workspace = true }
harp-benchmarks = { workspace = true }

[tool.uv.workspace]
members = [
    "src/packages/*",
]

[dependency-groups]
docs = [
    "griffe-fieldz>=0.2.1",
    "mkdocs>=1.6.1",
    "mkdocs-codeinclude-plugin>=0.2.1",
    "mkdocs-git-authors-plugin>=0.9.4",
    "mkdocs-include-markdown-plugin>=7.1.6",
    "mkdocs-material>=9.6.9",
    "mkdocstrings-python>=1.16.6",
]

dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.0",
    "ty>=0.0.0",
    "harp-protocol",
    "harp-device",
    "harp-serial",
    "harp-data",
    "harp-benchmarks",
    "typing-extensions>=4.15.0",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ["--import-mode=importlib", ]
python_files = [
    "tests.py",
    "test_*.py"
]


[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ty.environment]
python-version = "3.11"
extra-paths = ["tests"]

[tool.ty.src]
include = [
    "src/packages/harp-protocol/src",
    "src/packages/harp-device/src",
    "src/packages/harp-serial/src",
    "src/packages/harp-data/src",
]
exclude = [
    "tests",
]