"""The core register set every Harp device carries, and its address space."""

from ._register_map import REGISTER_MAP
from ._registers import (
    AssemblyVersion,
    ClockConfiguration,
    ClockConfigurationFlags,
    ClockConfigurationPayload,
    CoreVersionHigh,
    CoreVersionLow,
    DeviceName,
    DeviceNamePayload,
    EnableFlag,
    FirmwareVersionHigh,
    FirmwareVersionLow,
    HardwareVersionHigh,
    HardwareVersionLow,
    OperationControl,
    OperationControlPayload,
    OperationMode,
    ResetDevice,
    ResetDevicePayload,
    ResetFlags,
    SerialNumber,
    TimestampMicroseconds,
    TimestampSeconds,
    WhoAmI,
)

__all__ = [
    "REGISTER_MAP",
    "WhoAmI",
    "HardwareVersionHigh",
    "HardwareVersionLow",
    "AssemblyVersion",
    "CoreVersionHigh",
    "CoreVersionLow",
    "FirmwareVersionHigh",
    "FirmwareVersionLow",
    "TimestampSeconds",
    "TimestampMicroseconds",
    "OperationControl",
    "OperationControlPayload",
    "OperationMode",
    "ResetDevice",
    "ResetDevicePayload",
    "ResetFlags",
    "DeviceName",
    "DeviceNamePayload",
    "EnableFlag",
    "ClockConfiguration",
    "ClockConfigurationFlags",
    "ClockConfigurationPayload",
    "SerialNumber",
]
