from ._builder import build_message_frame
from ._checksum import compute as compute_checksum, validate as validate_checksum
from ._message import HarpMessage, HarpParseError, ParsedHarpMessage, parse as parse_message
from ._message_type import (
    MessageType,
    from_byte as message_type_from_byte,
    to_byte as message_type_to_byte,
)
from ._payload import (
    PayloadBase,
    PayloadU8,
    PayloadU16,
    PayloadU32,
    PayloadU64,
    PayloadS8,
    PayloadS16,
    PayloadS32,
    PayloadS64,
    PayloadFloat,
    PayloadU8Array,
    PayloadU16Array,
    PayloadU32Array,
    PayloadU64Array,
    PayloadS8Array,
    PayloadS16Array,
    PayloadS32Array,
    PayloadS64Array,
    PayloadFloatArray,
)
from ._payload_type import PayloadType, PayloadTypeInfo, decode_payload_type, encode_payload_type
from ._register import (
    RegisterBase,
    RegisterU8,
    RegisterU16,
    RegisterU32,
    RegisterU64,
    RegisterS8,
    RegisterS16,
    RegisterS32,
    RegisterS64,
    RegisterFloat,
    RegisterU8Array,
    RegisterU16Array,
    RegisterU32Array,
    RegisterU64Array,
    RegisterS8Array,
    RegisterS16Array,
    RegisterS32Array,
    RegisterS64Array,
    RegisterFloatArray,
)

__all__ = [
    # Message type
    "MessageType",
    "message_type_from_byte",
    "message_type_to_byte",
    # Payload type
    "PayloadType",
    "PayloadTypeInfo",
    "decode_payload_type",
    "encode_payload_type",
    # Checksum
    "compute_checksum",
    "validate_checksum",
    # Message
    "HarpMessage",
    "ParsedHarpMessage",
    "HarpParseError",
    "parse_message",
    # Payload DSL
    "PayloadBase",
    "PayloadU8",
    "PayloadU16",
    "PayloadU32",
    "PayloadU64",
    "PayloadS8",
    "PayloadS16",
    "PayloadS32",
    "PayloadS64",
    "PayloadFloat",
    "PayloadU8Array",
    "PayloadU16Array",
    "PayloadU32Array",
    "PayloadU64Array",
    "PayloadS8Array",
    "PayloadS16Array",
    "PayloadS32Array",
    "PayloadS64Array",
    "PayloadFloatArray",
    # Register DSL
    "RegisterBase",
    # Register scalar types
    "RegisterU8",
    "RegisterU16",
    "RegisterU32",
    "RegisterU64",
    "RegisterS8",
    "RegisterS16",
    "RegisterS32",
    "RegisterS64",
    "RegisterFloat",
    # Register array types
    "RegisterU8Array",
    "RegisterU16Array",
    "RegisterU32Array",
    "RegisterU64Array",
    "RegisterS8Array",
    "RegisterS16Array",
    "RegisterS32Array",
    "RegisterS64Array",
    "RegisterFloatArray",
    # Frame builders
    "build_message_frame",
]
