[project]
name = "harp-serial"
version = "0.3.0"
description = "Library for data acquisition and control of devices implementing the Harp protocol."
authors = [{ name= "Hardware and Software Platform, Champalimaud Foundation", email="software@research.fchampalimaud.org"}]
license = "MIT"
keywords = ['python', 'harp']
requires-python = ">=3.9,<4.0"
dependencies = [
    "harp-protocol==0.3.0",
    "pyserial>=3.5",
]

[tool.uv.sources]
harp-protocol = { workspace = true }

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "harp.serial"
module-root = ""
